### ISSUE TITLE
数据集测试阶段没有找到足够匹配点

### ISSUE THREAD

**Issue by baoyufuyou** [meiqua/patch_linemod#7]
我自己生成了一个数据集，用数据集里面的图像来测试。不过遇到了candidate size before refine and nms一直是0的情况。
然后我用test.cpp里面测试了一下。金字塔参数改成了{32, 64}之后才有多一点的匹配点。

**Comment by baoyufuyou** [comment]
![thumbnail_Image1](https://user-images.githubusercontent.com/39621208/112633843-28e0ca80-8e3a-11eb-847e-32df07aab378.jpg)

**Comment by meiqua** [comment]
感觉模板比物体小多了

**Comment by baoyufuyou** [comment]
@meiqua  那有可能是哪里的问题呢？是我训练时候的问题么？还是rendering部分参数设置的问题？

**Comment by meiqua** [comment]
可能模型原点在别的地方，导致渲染深度跟理解的不一样

**Comment by baoyufuyou** [comment]
@meiqua 我目前的原点的确是没有放在物体中心，多谢;)我再去生成一下。

**Comment by baoyufuyou** [comment]
@meiqua 我重新生成了一下，训练完之后预测还是检测不出来candidate。是不是因为我用的模型旋转对称，也没有texture？

**Comment by meiqua** [comment]
不会。一般要看模板跟实际图像里的大小是不是一致的

**Comment by baoyufuyou** [comment]
@meiqua 恩恩，我也觉得应该不会... 我刚刚又看了一下渲染出来的深度图，深度图变成了二值图，是不是渲染出来的深度图的问题？你之前有出现过这个问题么？

**Comment by baoyufuyou** [comment]
@meiqua 我看了一下，发现我用的不是最新的branch版本
